dist: bionic
os: linux
language: minimal
cache:
  ccache: true
  directories:
    - depends/built
    - depends/sdk-sources
    - $HOME/.ccache
env:
  global:
    - MAKEJOBS=-j3
    - BOOST_TEST_RANDOM=1$TRAVIS_BUILD_ID
    - CCACHE_SIZE=100M
    - CCACHE_TEMPDIR=/tmp/.ccache-temp
    - CCACHE_COMPRESS=1
    - CCACHE_DIR=$HOME/.ccache
    - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
    - SDK_URL=https://proteanx.com/sdk
    - WINEDEBUG=fixme-all
    - DOCKER_PACKAGES="build-essential libtool python3 python3-dev python3-setuptools cmake autotools-dev automake pkg-config bsdmainutils curl git ca-certificates ccache libgmp-dev"
before_install:
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/pyenv/d' | tr "\n" ":" | sed "s|::|:|g")
  - export PATH=$(echo "$PATH" | sed -e 's/:\/mnt.*//g')
  - set -o errexit; source .travis/beforeinstall.sh
install:
  - set -o errexit; source .travis/install.sh
before_script:
  - set -o errexit; source .travis/beforescript.sh
script:
  - if [ $SECONDS -gt 2000 ]; then set +o errexit; echo "exit to cache current state"; false; else set -o errexit; source .travis/script.sh; fi
after_script:
  - echo $TRAVIS_COMMIT_RANGE
  - echo $TRAVIS_COMMIT_LOG
jobs:
  include:

    - name: '64-bit Linux (debian buster)'
      env: >-
        HOST=x86_64-linux-gnu
        DOCKER_NAME_TAG=debian:10.3
        PACKAGES="python3-zmq qtbase5-dev qttools5-dev-tools qttools5-dev libevent-dev bsdmainutils libboost-all-dev libdb-dev libdb++-dev libminiupnpc-dev libzmq3-dev libqrencode-dev libsodium-dev libgmp-dev gperf"
        GOAL="install"
        CMAKE_OPT="Linux64.cmake"

    - name: 'Win64 (debian buster)'
      env: >-
        HOST=x86_64-w64-mingw32
        DOCKER_NAME_TAG=debian:10.3
        PACKAGES="python3 nsis wine-binfmt wine64 g++-mingw-w64-x86-64 gcc-mingw-w64-base gcc-mingw-w64-x86-64"
        GOAL="deploy"
        CMAKE_OPT="Win64.cmake"

    - name: 'MacOS (debian buster)'
      env: >-
        HOST=x86_64-apple-darwin14
        DOCKER_NAME_TAG=debian:10.3
        PACKAGES="python python-dev python3 python3-dev imagemagick libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools python3-setuptools-git ninja-build"
        OSX_SDK=10.14
        GOAL="deploy"
        CMAKE_OPT="OSX.cmake"

